name: fracevent
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - torch>=2.0
      - h5py
      - pyyaml
      - pillow
      - imageio
      - imageio-ffmpeg
      - -e .
